### ISSUE TITLE
ActiveFormModel + Administrate

### ISSUE THREAD

**Issue by JanaVPetrova** [Hexlet/active_form_model#10]
Привет!

Используем ActiveFormModel в связке с Administrate. Понадобились дополнительные валидации, которых нет в модели.

```ruby
# admin/entity_controller.rb

def create
  resource = Entity.new(resource_params)
  form = resource.becomes(EntityForm)
  
  if form.valid?
    resource.save!
    redirect_to([namespace, resource])
  else
    render(
      :new, 
      locals: { page: Administrate::Page::Form.new(dashboard, form) }, # строим страницу для form, чтобы правильно отображались ошибки валидации
      status: :unprocessable_entity
    )
  end
end
```

Форма в administrate выглядит [так](https://github.com/thoughtbot/administrate/blob/95922e736c1d8de093f578c94f27e0d351613785/app/views/administrate/application/_form.html.erb#L17)
```
# administrate/application/_form.html.erb
<%= form_for([namespace, page.resource], html: { class: "form" }) do |f| %>
  <% if page.resource.errors.any? %>
    ...
```

Получается, что форма строится для объекта `EntityForm` с соответствующим названием параметра `entity_form` и путем `entity_form_path`, которого не существует. Чтобы решить эту проблему, мы пока переопределяем `EntityForm.model_name`, иначе приходится и вьюхи переписывать вслед за экшеном:

```ruby
class EntityForm < Entity
  include ActiveFormModel

  def self.model_name
    ActiveModel::Name.new(self, nil, Entity.name)
  end

  # ...
end
```

Предлагаю внести это в `ActiveFormModel`.

**Comment by mokevnin** [comment]
sent a little fix, try it before release

**Comment by inem** [comment]
Кирилл, как тебе идея зашить внутрь еще `self.policy_class` на базе предка, чтобы не приходилось в форму такое добавлять для `authorize @form`:

![image](https://user-images.githubusercontent.com/9665/124256597-c7f91a80-db2b-11eb-84cd-0e8fe1da51e9.png)

Хотя может оно и так будет с последним изменением работать, не смотрел как pundit устроен в этом месте.

**Comment by igor-i** [comment]
я проверил, такое больше не нужно делать

**Comment by igor-i** [comment]
> Кирилл, как тебе идея зашить внутрь еще `self.policy_class` на базе предка, чтобы не приходилось в форму такое добавлять для `authorize @form`:
> 
> ![image](https://user-images.githubusercontent.com/9665/124256597-c7f91a80-db2b-11eb-84cd-0e8fe1da51e9.png)
> 
> Хотя может оно и так будет с последним изменением работать, не смотрел как pundit устроен в этом месте.

я првоерил, такое больше не нужно делать

**Comment by igor-i** [comment]
думаю стоит упомянуть, что это изменение аффектит ещё другие пару мест:
- из формы в контроллер параметры теперь приходят без постфикса `_form` (то есть если раньше было `params[:entity_form]`, то теперь будет `params[:entity]`);
- меняются неймспейсы переводов (I18n), например, ошибок валидации active_record (которые определены в форме) или атрибутов simple_form

кстати, для атрибутов simple_form это не всегда хорошо, так как переводы лейблов полей, плейсхолдеров и тп теперь всегда будут общими для всех форм наследуемых от одной модели

**Comment by mokevnin** [comment]
ох точно, именно поэтому я его и отменил. Откатываю.
